### ISSUE TITLE
Contact info

### ISSUE THREAD

**Issue by atomass** [Stolas/wordlist#1]
Hi @Stolas ,
I've tried other ways to contact you but I couldn't find any email address so... 
I'm contacting you about a reply you leave on [reverseengineering.stackexchange.com](http://reverseengineering.stackexchange.com/questions/5948/using-stunnel-to-packet-capture-https-connection/5988#5988) 
I've tried myself the way you suggested but I'm facing some troubles. I've downloaded and compiled openssl for android and I've inserted some lines to dump to file http requests. I've modified `bio_lib.c` and `bio_ssl.c` then I've pushed `libcrypto.so` and `libssl.so` to the emulator but than nothing was written to the dump file.
The app I'm trying to reverse engineering is using OkHttpClient (if this really matters).
My problems are: when I reboot the emulator all changes to /system are gone and I'm not sure about the correctness of my changes to the openssl lib (maybe I should dump the http request elsewhere?!)

Bye,
Andrea

**Comment by Stolas** [comment]
This is not the place to exchange email addresses, comment your info on stackexchange and I'll get back to you.

**Comment by atomass** [comment]
The fact is that I'm mainly active on StackOverflow so I don't have not enough reputation on StackExchange to leave a comment... That's the only reason why I'm posting here my question.

**Comment by Stolas** [comment]
Post your contact info here and I'll contact you.

**Comment by atomass** [comment]
Thank you very much for your kindness
my email is tomassetti.andrea[at]gmail[dot]com
